registrySecretName: my-docker-secret

replicaCount: 2
weatherApp:
  image:
    repository: yossizxc/weather_app
    pullPolicy: IfNotPresent
    tag: 7b9641
  service:
    type: NodePort
    port: 80
    targetPort: 5000
    nodePort: 32300


serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""


ingressController:
  enabled: false
