registrySecretName: my-docker-secret

replicaCount: 2
weatherApp:
  image:
    repository: registry.gitlab.com/kojoey/weather # yossizxc/weather
    pullPolicy: IfNotPresent
    tag: bf26667
  service:
    type: LoadBalancer
    port: 80
    targetPort: 5000


serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""


ingressController:
  enabled: false
