version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            ls
            pwd
            cd src
            docker-compose build
      - run:
          name: Run Docker Compose
          command: |
            cd src
            docker-compose down
            docker-compose --compatibility up -d
      - run:
          name: Wait for Services to Start
          command: sleep 3
      - run:
          name: Run Tests
          command: |
            cd src
            ./tests/unittest.sh
      - run:
          name: Docker Compose Down
          command: |
            cd src
            docker-compose down

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test
