version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            ls
            pwd
            cd src
            docker-compose build
      - run:
          name: Run Docker Compose
          command: |
            cd src
            docker-compose down
            docker-compose --compatibility up -d
      - run:
          name: Wait for Services to Start
          command: sleep 3
      - run:
          name: Run Tests
          command: |
            cd src
            docker ps 
            # bash ./tests/unittest.sh
      - run:
          name: Docker Compose Down
          command: |
            cd src
            docker-compose down
  publish:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            cd src
            docker-compose build
      - run:
          name: Login to GitLab Container Registry
          command: |
            echo ${GITLAB_TOKEN}
            echo $GITLAB_USER
            echo $GITLAB_REGISTRY
            echo $GITLAB_PROJECT
            echo $GITLAB_TOKEN | docker login -u $GITLAB_USER --password-stdin $GITLAB_REGISTRY
      - run:
          name: Tag and Push Docker Image
          command: |
            docker tag src_gunicorn:latest registry.gitlab.com/kojoey/weather:latest
            docker images
            docker push registry.gitlab.com/kojoey/weather:latest    

workflows:
  version: 2
  build_and_test_push_workflow:
    jobs:
      # - build_and_test
      - publish 
          # requires:
          #   - build_and_test
