apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weather-app
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-weather-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-weather-app
    spec:
      imagePullSecrets:
          - name: {{ .Values.registrySecretName }}
      containers:
        - name: weather-app
          image: {{ .Values.weatherApp.image.repository }}:{{ .Values.weatherApp.image.tag }}
          imagePullPolicy: {{ .Values.weatherApp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.weatherApp.service.targetPort }}
          env:
            - name: BG_COLOR
              valueFrom:
                configMapKeyRef:
                  name: configmap-blue
                  key: BG_COLOR
