name: semantic

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure all tags and history are fetched

      - name: Determine semantic version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          namespace: weather
          enable_prerelease_mode: true
          debug: true

      - name: Output version
        run: echo "Determined version is ${{ steps.version.outputs.version }}"

      - name: Create new tag
        if: steps.version.outputs.new_tag == 'true'
        run: git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Push new tag
        if: steps.version.outputs.new_tag == 'true'
        run: git push origin ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
