name: semantic

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure all tags and history are fetched

      - name: Determine semantic version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          namespace: weather
          enable_prerelease_mode: false  # Temporarily disable prerelease to simplify

      - name: Output version info
        run: |
          echo "New Tag: ${{ steps.version.outputs.new_tag }}"
          echo "New Version: ${{ steps.version.outputs.version }}"
          echo "Commit SHA: ${{ steps.version.outputs.commit_sha }}"

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create new tag
        if: steps.version.outputs.new_tag == 'true'
        run: git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new tag
        if: steps.version.outputs.new_tag == 'true'
        run: git push origin ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
