name: Bump version and push tag

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Determine version bump
        id: get_bump
        run: |
          if git log -1 --pretty=%B | grep -q '\[MAJOR\]'; then
            echo "bump=major" >> $GITHUB_ENV
          elif git log -1 --pretty=%B | grep -q '\[MINOR\]'; then
            echo "bump=minor" >> $GITHUB_ENV
          else
            echo "bump=patch" >> $GITHUB_ENV
          fi

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          default_bump: ${{ env.bump }}
          commit_sha: ${{ github.sha }}

      - name: Push changes
        run: git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
