name: Tag version

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine version bump
        id: get_bump
        run: |
          if git log -1 --pretty=%B | grep -q '\[MAJOR\]'; then
            echo "bump=major" >> $GITHUB_ENV
          elif git log -1 --pretty=%B | grep -q '\[MINOR\]'; then
            echo "bump=minor" >> $GITHUB_ENV
          else
            echo "bump=patch" >> $GITHUB_ENV

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.40.0
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          default_bump: ${{ env.bump }}
          tag_prefix: "v"

      - name: Push changes
        run: git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
