name: UpdateManifest Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm-chart/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: ./src
        run: |
          docker-compose build
          SHORT_SHA=$(echo "${GITHUB_SHA}" | head -c 6)
          IMAGE="yossizxc/weather:${SHORT_SHA}"
          docker tag src_gunicorn:latest $IMAGE
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE }}

      - name: Update Helm values.yaml
        run: |
          sed -i 's|tag:.*|tag: '"${{ env.SHORT_SHA }}"'|' ./helm-chart/values.yaml

      - name: Commit and push changes to values.yaml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image tag to ${{ env.SHORT_SHA }}"
          branch: main
          file_pattern: ./helm-chart/values.yaml
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
