name: Main Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed
  repository_dispatch:
    types: [ deploy ]
  push:
    branches:
      - master
    paths-ignore:
      - 'helm-chart/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: ./src
        run: |
          docker-compose build
          IMAGE_TAG=$(docker-compose images | grep weather_app | awk '{print $3}')
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Debug IMAGE_TAG
        run: echo ${{ env.IMAGE_TAG }}

      - name: Push Docker Image
        run: |
          docker tag ${{ env.IMAGE_TAG }} yossizxc/weather_app:my-app-${{ github.sha }}
          docker push yossizxc/weather_app:my-app-${{ github.sha }}

      - name: Update Helm values.yaml
        run: |
          sed -i 's/tag:.*/tag: my-app-${{ github.sha }}/' ./helm-chart/values.yaml

      - name: Commit and push changes to values.yaml
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./helm-chart/values.yaml
          git commit -m "Update image tag to my-app-${{ github.sha }}"
          git push
