name: UpdateManifest Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm-chart/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: ./src
        run: |
          docker-compose build
          SHORT_SHA=$(echo "${GITHUB_SHA}" | head -c 6)
          IMAGE="yossizxc/weather_app:${SHORT_SHA}"
          docker tag src_gunicorn:latest $IMAGE
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE }}

      - name: Update Helm values.yaml
        run: |
          sed -i 's|tag:.*|tag: '"${{ env.SHORT_SHA }}"'|' ./helm-chart/values.yaml

      - name: Commit and push changes to values.yaml
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./helm-chart/values.yaml
          git commit -m "Update image tag to my-app-${{ env.IMAGE_TAG }}"
          git push https://x-access-token:${REPO_ACCESS_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
